/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mdsd.parser.antlr.internal.InternalCSVParserGeneratorParser;
import dk.sdu.mdsd.services.CSVParserGeneratorGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CSVParserGeneratorParser extends AbstractAntlrParser {

	@Inject
	private CSVParserGeneratorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCSVParserGeneratorParser createParser(XtextTokenStream stream) {
		return new InternalCSVParserGeneratorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Parser";
	}

	public CSVParserGeneratorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CSVParserGeneratorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
