/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.ide;


/**
 * Use this class to register ide components.
 */
public class CSVParserGeneratorIdeModule extends AbstractCSVParserGeneratorIdeModule {
}
