/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class CSVParserGeneratorProposalProvider extends AbstractCSVParserGeneratorProposalProvider {
}
