/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.generator;

import dk.sdu.mdsd.generator.ParserClassGenerator;
import javax.inject.Inject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class CSVParserGeneratorGenerator extends AbstractGenerator {
  @Inject
  @Extension
  private ParserClassGenerator parserGenerator;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    fsa.generateFile("/parser/pom.xml", this.generatePom());
    this.parserGenerator.doGenerate(resource, fsa, context);
  }
  
  public Object generateProjectStructure(final IFileSystemAccess2 fsa) {
    return null;
  }
  
  public CharSequence generatePom() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
    _builder.newLine();
    _builder.append("<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<modelVersion>4.0.0</modelVersion>");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<groupId>dk.sdu.mmmi.parser</groupId>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<artifactId>demo</artifactId>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<version>0.0.1-SNAPSHOT</version>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<name>GeneratedParser</name>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<description>GeneratedParser</description>");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<properties>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<java.version>8</java.version>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</properties>");
    _builder.newLine();
    _builder.append("  ");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<dependencies>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<dependency>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<groupId>org.apache.commons</groupId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<artifactId>commons-csv</artifactId>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<version>1.8</version>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</dependency>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</dependencies>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<build>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</build>");
    _builder.newLine();
    _builder.append("</project>");
    _builder.newLine();
    return _builder;
  }
}
