/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.cSVParserGenerator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.cSVParserGenerator.CSVParserGeneratorPackage#getColumnAction()
 * @model
 * @generated
 */
public interface ColumnAction extends Modification
{
} // ColumnAction
