/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.cSVParserGenerator;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constrain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.cSVParserGenerator.Constrain#getMods <em>Mods</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.cSVParserGenerator.CSVParserGeneratorPackage#getConstrain()
 * @model
 * @generated
 */
public interface Constrain extends Modification
{
  /**
   * Returns the value of the '<em><b>Mods</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mdsd.cSVParserGenerator.Constraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mods</em>' containment reference list.
   * @see dk.sdu.mdsd.cSVParserGenerator.CSVParserGeneratorPackage#getConstrain_Mods()
   * @model containment="true"
   * @generated
   */
  EList<Constraint> getMods();

} // Constrain
