/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.cSVParserGenerator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dk.sdu.mdsd.cSVParserGenerator.CSVParserGeneratorFactory
 * @model kind="package"
 * @generated
 */
public interface CSVParserGeneratorPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cSVParserGenerator";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sdu.dk/mdsd/CSVParserGenerator";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cSVParserGenerator";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CSVParserGeneratorPackage eINSTANCE = dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl.init();

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ParserImpl <em>Parser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ParserImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getParser()
   * @generated
   */
  int PARSER = 0;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARSER__FILE = 0;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARSER__COLUMNS = 1;

  /**
   * The feature id for the '<em><b>Mods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARSER__MODS = 2;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARSER__OUT = 3;

  /**
   * The number of structural features of the '<em>Parser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARSER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.FileDeclImpl <em>File Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.FileDeclImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getFileDecl()
   * @generated
   */
  int FILE_DECL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_DECL__NAME = 0;

  /**
   * The number of structural features of the '<em>File Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_DECL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ColDeclImpl <em>Col Decl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ColDeclImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getColDecl()
   * @generated
   */
  int COL_DECL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_DECL__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_DECL__TYPE = 1;

  /**
   * The feature id for the '<em><b>Mods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_DECL__MODS = 2;

  /**
   * The number of structural features of the '<em>Col Decl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_DECL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ModificationImpl <em>Modification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ModificationImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getModification()
   * @generated
   */
  int MODIFICATION = 3;

  /**
   * The number of structural features of the '<em>Modification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFICATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.OutputImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__NAME = 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ValueModImpl <em>Value Mod</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ValueModImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getValueMod()
   * @generated
   */
  int VALUE_MOD = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_MOD__NAME = MODIFICATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_MOD__EXP = MODIFICATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Value Mod</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_MOD_FEATURE_COUNT = MODIFICATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.TypeImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getType()
   * @generated
   */
  int TYPE = 6;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ExpressionImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 7;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ParensImpl <em>Parens</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ParensImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getParens()
   * @generated
   */
  int PARENS = 8;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENS__EXP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parens</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ExternalImpl <em>External</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ExternalImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getExternal()
   * @generated
   */
  int EXTERNAL = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL__NAME = MODIFICATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Inp</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL__INP = MODIFICATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>External</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTERNAL_FEATURE_COUNT = MODIFICATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.StatFuncImpl <em>Stat Func</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.StatFuncImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getStatFunc()
   * @generated
   */
  int STAT_FUNC = 10;

  /**
   * The feature id for the '<em><b>Input</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAT_FUNC__INPUT = MODIFICATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Stat Func</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAT_FUNC_FEATURE_COUNT = MODIFICATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ColumnActionImpl <em>Column Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ColumnActionImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getColumnAction()
   * @generated
   */
  int COLUMN_ACTION = 11;

  /**
   * The number of structural features of the '<em>Column Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_ACTION_FEATURE_COUNT = MODIFICATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ColumnVarImpl <em>Column Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ColumnVarImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getColumnVar()
   * @generated
   */
  int COLUMN_VAR = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_VAR__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Column Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_VAR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.NumberImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 13;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ConstraintImpl <em>Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.ConstraintImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getConstraint()
   * @generated
   */
  int CONSTRAINT = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__NAME = MODIFICATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT__EXP = MODIFICATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTRAINT_FEATURE_COUNT = MODIFICATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.StrImpl <em>Str</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.StrImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getStr()
   * @generated
   */
  int STR = 15;

  /**
   * The number of structural features of the '<em>Str</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STR_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.IntegerImpl <em>Integer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.IntegerImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getInteger()
   * @generated
   */
  int INTEGER = 16;

  /**
   * The number of structural features of the '<em>Integer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.DateImpl <em>Date</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.DateImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getDate()
   * @generated
   */
  int DATE = 17;

  /**
   * The number of structural features of the '<em>Date</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.FloatImpl <em>Float</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.FloatImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getFloat()
   * @generated
   */
  int FLOAT = 18;

  /**
   * The number of structural features of the '<em>Float</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.OrImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getOr()
   * @generated
   */
  int OR = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.AndImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getAnd()
   * @generated
   */
  int AND = 20;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.LtImpl <em>Lt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.LtImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getLt()
   * @generated
   */
  int LT = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Lt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.GtImpl <em>Gt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.GtImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getGt()
   * @generated
   */
  int GT = 22;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Gt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.EquImpl <em>Equ</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.EquImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getEqu()
   * @generated
   */
  int EQU = 23;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Equ</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQU_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.NeqImpl <em>Neq</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.NeqImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getNeq()
   * @generated
   */
  int NEQ = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Neq</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.LeqImpl <em>Leq</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.LeqImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getLeq()
   * @generated
   */
  int LEQ = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEQ__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEQ__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Leq</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEQ_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.GeqImpl <em>Geq</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.GeqImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getGeq()
   * @generated
   */
  int GEQ = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEQ__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEQ__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Geq</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEQ_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MaxImpl <em>Max</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.MaxImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMax()
   * @generated
   */
  int MAX = 27;

  /**
   * The feature id for the '<em><b>Input</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX__INPUT = STAT_FUNC__INPUT;

  /**
   * The number of structural features of the '<em>Max</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_FEATURE_COUNT = STAT_FUNC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MinImpl <em>Min</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.MinImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMin()
   * @generated
   */
  int MIN = 28;

  /**
   * The feature id for the '<em><b>Input</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN__INPUT = STAT_FUNC__INPUT;

  /**
   * The number of structural features of the '<em>Min</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_FEATURE_COUNT = STAT_FUNC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.StdImpl <em>Std</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.StdImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getStd()
   * @generated
   */
  int STD = 29;

  /**
   * The feature id for the '<em><b>Input</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STD__INPUT = STAT_FUNC__INPUT;

  /**
   * The number of structural features of the '<em>Std</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STD_FEATURE_COUNT = STAT_FUNC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.SumFuncImpl <em>Sum Func</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.SumFuncImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getSumFunc()
   * @generated
   */
  int SUM_FUNC = 30;

  /**
   * The feature id for the '<em><b>Input</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM_FUNC__INPUT = STAT_FUNC__INPUT;

  /**
   * The number of structural features of the '<em>Sum Func</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM_FUNC_FEATURE_COUNT = STAT_FUNC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MeanImpl <em>Mean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.MeanImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMean()
   * @generated
   */
  int MEAN = 31;

  /**
   * The feature id for the '<em><b>Input</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEAN__INPUT = STAT_FUNC__INPUT;

  /**
   * The number of structural features of the '<em>Mean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEAN_FEATURE_COUNT = STAT_FUNC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.AddImpl <em>Add</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.AddImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getAdd()
   * @generated
   */
  int ADD = 32;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__NAME = COLUMN_ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Mod</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD__MOD = COLUMN_ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FEATURE_COUNT = COLUMN_ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.RemImpl <em>Rem</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.RemImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getRem()
   * @generated
   */
  int REM = 33;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REM__NAME = COLUMN_ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rem</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REM_FEATURE_COUNT = COLUMN_ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.PlusImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getPlus()
   * @generated
   */
  int PLUS = 34;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.MinusImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMinus()
   * @generated
   */
  int MINUS = 35;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MultImpl <em>Mult</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.MultImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMult()
   * @generated
   */
  int MULT = 36;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Mult</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.DivImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getDiv()
   * @generated
   */
  int DIV = 37;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.NumImpl <em>Num</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.NumImpl
   * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getNum()
   * @generated
   */
  int NUM = 38;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUM__VALUE = NUMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Num</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUM_FEATURE_COUNT = NUMBER_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Parser <em>Parser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parser</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Parser
   * @generated
   */
  EClass getParser();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Parser#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Parser#getFile()
   * @see #getParser()
   * @generated
   */
  EReference getParser_File();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.cSVParserGenerator.Parser#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Parser#getColumns()
   * @see #getParser()
   * @generated
   */
  EReference getParser_Columns();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.cSVParserGenerator.Parser#getMods <em>Mods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mods</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Parser#getMods()
   * @see #getParser()
   * @generated
   */
  EReference getParser_Mods();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Parser#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Out</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Parser#getOut()
   * @see #getParser()
   * @generated
   */
  EReference getParser_Out();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.FileDecl <em>File Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>File Decl</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.FileDecl
   * @generated
   */
  EClass getFileDecl();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.cSVParserGenerator.FileDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.FileDecl#getName()
   * @see #getFileDecl()
   * @generated
   */
  EAttribute getFileDecl_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.ColDecl <em>Col Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Col Decl</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ColDecl
   * @generated
   */
  EClass getColDecl();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.cSVParserGenerator.ColDecl#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ColDecl#getName()
   * @see #getColDecl()
   * @generated
   */
  EAttribute getColDecl_Name();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.ColDecl#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ColDecl#getType()
   * @see #getColDecl()
   * @generated
   */
  EReference getColDecl_Type();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.cSVParserGenerator.ColDecl#getMods <em>Mods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mods</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ColDecl#getMods()
   * @see #getColDecl()
   * @generated
   */
  EReference getColDecl_Mods();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Modification <em>Modification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modification</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Modification
   * @generated
   */
  EClass getModification();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.cSVParserGenerator.Output#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Output#getName()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.ValueMod <em>Value Mod</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value Mod</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ValueMod
   * @generated
   */
  EClass getValueMod();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.cSVParserGenerator.ValueMod#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ValueMod#getName()
   * @see #getValueMod()
   * @generated
   */
  EReference getValueMod_Name();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.ValueMod#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ValueMod#getExp()
   * @see #getValueMod()
   * @generated
   */
  EReference getValueMod_Exp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Parens <em>Parens</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parens</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Parens
   * @generated
   */
  EClass getParens();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Parens#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Parens#getExp()
   * @see #getParens()
   * @generated
   */
  EReference getParens_Exp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.External <em>External</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>External</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.External
   * @generated
   */
  EClass getExternal();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.cSVParserGenerator.External#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.External#getName()
   * @see #getExternal()
   * @generated
   */
  EAttribute getExternal_Name();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.cSVParserGenerator.External#getInp <em>Inp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Inp</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.External#getInp()
   * @see #getExternal()
   * @generated
   */
  EReference getExternal_Inp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.StatFunc <em>Stat Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stat Func</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.StatFunc
   * @generated
   */
  EClass getStatFunc();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.cSVParserGenerator.StatFunc#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Input</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.StatFunc#getInput()
   * @see #getStatFunc()
   * @generated
   */
  EReference getStatFunc_Input();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.ColumnAction <em>Column Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column Action</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ColumnAction
   * @generated
   */
  EClass getColumnAction();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.ColumnVar <em>Column Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column Var</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ColumnVar
   * @generated
   */
  EClass getColumnVar();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.cSVParserGenerator.ColumnVar#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.ColumnVar#getName()
   * @see #getColumnVar()
   * @generated
   */
  EReference getColumnVar_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Constraint <em>Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constraint</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Constraint
   * @generated
   */
  EClass getConstraint();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.cSVParserGenerator.Constraint#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Constraint#getName()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_Name();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Constraint#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Constraint#getExp()
   * @see #getConstraint()
   * @generated
   */
  EReference getConstraint_Exp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Str <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Str</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Str
   * @generated
   */
  EClass getStr();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Integer <em>Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Integer
   * @generated
   */
  EClass getInteger();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Date <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Date</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Date
   * @generated
   */
  EClass getDate();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Float <em>Float</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Float</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Float
   * @generated
   */
  EClass getFloat();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Lt <em>Lt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lt</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Lt
   * @generated
   */
  EClass getLt();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Lt#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Lt#getLeft()
   * @see #getLt()
   * @generated
   */
  EReference getLt_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Lt#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Lt#getRight()
   * @see #getLt()
   * @generated
   */
  EReference getLt_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Gt <em>Gt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gt</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Gt
   * @generated
   */
  EClass getGt();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Gt#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Gt#getLeft()
   * @see #getGt()
   * @generated
   */
  EReference getGt_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Gt#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Gt#getRight()
   * @see #getGt()
   * @generated
   */
  EReference getGt_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Equ <em>Equ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equ</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Equ
   * @generated
   */
  EClass getEqu();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Equ#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Equ#getLeft()
   * @see #getEqu()
   * @generated
   */
  EReference getEqu_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Equ#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Equ#getRight()
   * @see #getEqu()
   * @generated
   */
  EReference getEqu_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Neq <em>Neq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Neq</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Neq
   * @generated
   */
  EClass getNeq();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Neq#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Neq#getLeft()
   * @see #getNeq()
   * @generated
   */
  EReference getNeq_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Neq#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Neq#getRight()
   * @see #getNeq()
   * @generated
   */
  EReference getNeq_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Leq <em>Leq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Leq</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Leq
   * @generated
   */
  EClass getLeq();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Leq#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Leq#getLeft()
   * @see #getLeq()
   * @generated
   */
  EReference getLeq_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Leq#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Leq#getRight()
   * @see #getLeq()
   * @generated
   */
  EReference getLeq_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Geq <em>Geq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Geq</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Geq
   * @generated
   */
  EClass getGeq();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Geq#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Geq#getLeft()
   * @see #getGeq()
   * @generated
   */
  EReference getGeq_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Geq#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Geq#getRight()
   * @see #getGeq()
   * @generated
   */
  EReference getGeq_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Max <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Max</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Max
   * @generated
   */
  EClass getMax();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Min <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Min</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Min
   * @generated
   */
  EClass getMin();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Std <em>Std</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Std</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Std
   * @generated
   */
  EClass getStd();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.SumFunc <em>Sum Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sum Func</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.SumFunc
   * @generated
   */
  EClass getSumFunc();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Mean <em>Mean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mean</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Mean
   * @generated
   */
  EClass getMean();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Add <em>Add</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Add
   * @generated
   */
  EClass getAdd();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.cSVParserGenerator.Add#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Add#getName()
   * @see #getAdd()
   * @generated
   */
  EAttribute getAdd_Name();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Add#getMod <em>Mod</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mod</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Add#getMod()
   * @see #getAdd()
   * @generated
   */
  EReference getAdd_Mod();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Rem <em>Rem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rem</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Rem
   * @generated
   */
  EClass getRem();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.cSVParserGenerator.Rem#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Rem#getName()
   * @see #getRem()
   * @generated
   */
  EReference getRem_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Mult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Mult
   * @generated
   */
  EClass getMult();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Mult#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Mult#getLeft()
   * @see #getMult()
   * @generated
   */
  EReference getMult_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Mult#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Mult#getRight()
   * @see #getMult()
   * @generated
   */
  EReference getMult_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Div#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Div#getLeft()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.cSVParserGenerator.Div#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Div#getRight()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.cSVParserGenerator.Num <em>Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Num</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Num
   * @generated
   */
  EClass getNum();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.cSVParserGenerator.Num#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mdsd.cSVParserGenerator.Num#getValue()
   * @see #getNum()
   * @generated
   */
  EAttribute getNum_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CSVParserGeneratorFactory getCSVParserGeneratorFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ParserImpl <em>Parser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ParserImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getParser()
     * @generated
     */
    EClass PARSER = eINSTANCE.getParser();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARSER__FILE = eINSTANCE.getParser_File();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARSER__COLUMNS = eINSTANCE.getParser_Columns();

    /**
     * The meta object literal for the '<em><b>Mods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARSER__MODS = eINSTANCE.getParser_Mods();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARSER__OUT = eINSTANCE.getParser_Out();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.FileDeclImpl <em>File Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.FileDeclImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getFileDecl()
     * @generated
     */
    EClass FILE_DECL = eINSTANCE.getFileDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILE_DECL__NAME = eINSTANCE.getFileDecl_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ColDeclImpl <em>Col Decl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ColDeclImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getColDecl()
     * @generated
     */
    EClass COL_DECL = eINSTANCE.getColDecl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COL_DECL__NAME = eINSTANCE.getColDecl_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COL_DECL__TYPE = eINSTANCE.getColDecl_Type();

    /**
     * The meta object literal for the '<em><b>Mods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COL_DECL__MODS = eINSTANCE.getColDecl_Mods();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ModificationImpl <em>Modification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ModificationImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getModification()
     * @generated
     */
    EClass MODIFICATION = eINSTANCE.getModification();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.OutputImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__NAME = eINSTANCE.getOutput_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ValueModImpl <em>Value Mod</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ValueModImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getValueMod()
     * @generated
     */
    EClass VALUE_MOD = eINSTANCE.getValueMod();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE_MOD__NAME = eINSTANCE.getValueMod_Name();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE_MOD__EXP = eINSTANCE.getValueMod_Exp();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.TypeImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ExpressionImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ParensImpl <em>Parens</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ParensImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getParens()
     * @generated
     */
    EClass PARENS = eINSTANCE.getParens();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENS__EXP = eINSTANCE.getParens_Exp();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ExternalImpl <em>External</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ExternalImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getExternal()
     * @generated
     */
    EClass EXTERNAL = eINSTANCE.getExternal();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTERNAL__NAME = eINSTANCE.getExternal_Name();

    /**
     * The meta object literal for the '<em><b>Inp</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTERNAL__INP = eINSTANCE.getExternal_Inp();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.StatFuncImpl <em>Stat Func</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.StatFuncImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getStatFunc()
     * @generated
     */
    EClass STAT_FUNC = eINSTANCE.getStatFunc();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STAT_FUNC__INPUT = eINSTANCE.getStatFunc_Input();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ColumnActionImpl <em>Column Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ColumnActionImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getColumnAction()
     * @generated
     */
    EClass COLUMN_ACTION = eINSTANCE.getColumnAction();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ColumnVarImpl <em>Column Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ColumnVarImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getColumnVar()
     * @generated
     */
    EClass COLUMN_VAR = eINSTANCE.getColumnVar();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN_VAR__NAME = eINSTANCE.getColumnVar_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.NumberImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.ConstraintImpl <em>Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.ConstraintImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getConstraint()
     * @generated
     */
    EClass CONSTRAINT = eINSTANCE.getConstraint();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__NAME = eINSTANCE.getConstraint_Name();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTRAINT__EXP = eINSTANCE.getConstraint_Exp();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.StrImpl <em>Str</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.StrImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getStr()
     * @generated
     */
    EClass STR = eINSTANCE.getStr();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.IntegerImpl <em>Integer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.IntegerImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getInteger()
     * @generated
     */
    EClass INTEGER = eINSTANCE.getInteger();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.DateImpl <em>Date</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.DateImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getDate()
     * @generated
     */
    EClass DATE = eINSTANCE.getDate();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.FloatImpl <em>Float</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.FloatImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getFloat()
     * @generated
     */
    EClass FLOAT = eINSTANCE.getFloat();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.OrImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.AndImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.LtImpl <em>Lt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.LtImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getLt()
     * @generated
     */
    EClass LT = eINSTANCE.getLt();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LT__LEFT = eINSTANCE.getLt_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LT__RIGHT = eINSTANCE.getLt_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.GtImpl <em>Gt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.GtImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getGt()
     * @generated
     */
    EClass GT = eINSTANCE.getGt();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GT__LEFT = eINSTANCE.getGt_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GT__RIGHT = eINSTANCE.getGt_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.EquImpl <em>Equ</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.EquImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getEqu()
     * @generated
     */
    EClass EQU = eINSTANCE.getEqu();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQU__LEFT = eINSTANCE.getEqu_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQU__RIGHT = eINSTANCE.getEqu_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.NeqImpl <em>Neq</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.NeqImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getNeq()
     * @generated
     */
    EClass NEQ = eINSTANCE.getNeq();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEQ__LEFT = eINSTANCE.getNeq_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEQ__RIGHT = eINSTANCE.getNeq_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.LeqImpl <em>Leq</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.LeqImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getLeq()
     * @generated
     */
    EClass LEQ = eINSTANCE.getLeq();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEQ__LEFT = eINSTANCE.getLeq_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEQ__RIGHT = eINSTANCE.getLeq_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.GeqImpl <em>Geq</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.GeqImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getGeq()
     * @generated
     */
    EClass GEQ = eINSTANCE.getGeq();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GEQ__LEFT = eINSTANCE.getGeq_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GEQ__RIGHT = eINSTANCE.getGeq_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MaxImpl <em>Max</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.MaxImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMax()
     * @generated
     */
    EClass MAX = eINSTANCE.getMax();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MinImpl <em>Min</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.MinImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMin()
     * @generated
     */
    EClass MIN = eINSTANCE.getMin();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.StdImpl <em>Std</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.StdImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getStd()
     * @generated
     */
    EClass STD = eINSTANCE.getStd();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.SumFuncImpl <em>Sum Func</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.SumFuncImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getSumFunc()
     * @generated
     */
    EClass SUM_FUNC = eINSTANCE.getSumFunc();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MeanImpl <em>Mean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.MeanImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMean()
     * @generated
     */
    EClass MEAN = eINSTANCE.getMean();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.AddImpl <em>Add</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.AddImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getAdd()
     * @generated
     */
    EClass ADD = eINSTANCE.getAdd();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD__NAME = eINSTANCE.getAdd_Name();

    /**
     * The meta object literal for the '<em><b>Mod</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD__MOD = eINSTANCE.getAdd_Mod();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.RemImpl <em>Rem</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.RemImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getRem()
     * @generated
     */
    EClass REM = eINSTANCE.getRem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REM__NAME = eINSTANCE.getRem_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.PlusImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.MinusImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.MultImpl <em>Mult</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.MultImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getMult()
     * @generated
     */
    EClass MULT = eINSTANCE.getMult();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__LEFT = eINSTANCE.getMult_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__RIGHT = eINSTANCE.getMult_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.DivImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__LEFT = eINSTANCE.getDiv_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__RIGHT = eINSTANCE.getDiv_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.cSVParserGenerator.impl.NumImpl <em>Num</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.NumImpl
     * @see dk.sdu.mdsd.cSVParserGenerator.impl.CSVParserGeneratorPackageImpl#getNum()
     * @generated
     */
    EClass NUM = eINSTANCE.getNum();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUM__VALUE = eINSTANCE.getNum_Value();

  }

} //CSVParserGeneratorPackage
