/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.cSVParserGenerator;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rem</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.cSVParserGenerator.Rem#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.cSVParserGenerator.CSVParserGeneratorPackage#getRem()
 * @model
 * @generated
 */
public interface Rem extends ColumnAction
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(ColDecl)
   * @see dk.sdu.mdsd.cSVParserGenerator.CSVParserGeneratorPackage#getRem_Name()
   * @model
   * @generated
   */
  ColDecl getName();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.cSVParserGenerator.Rem#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(ColDecl value);

} // Rem
