/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.cSVParserGenerator;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stat Func</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.cSVParserGenerator.StatFunc#getInput <em>Input</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.cSVParserGenerator.CSVParserGeneratorPackage#getStatFunc()
 * @model
 * @generated
 */
public interface StatFunc extends EObject
{
  /**
   * Returns the value of the '<em><b>Input</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' reference.
   * @see #setInput(ColDecl)
   * @see dk.sdu.mdsd.cSVParserGenerator.CSVParserGeneratorPackage#getStatFunc_Input()
   * @model
   * @generated
   */
  ColDecl getInput();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.cSVParserGenerator.StatFunc#getInput <em>Input</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input</em>' reference.
   * @see #getInput()
   * @generated
   */
  void setInput(ColDecl value);

} // StatFunc
