/**
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.tests;

import com.google.inject.Inject;
import dk.sdu.mdsd.tests.CSVParserGeneratorInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(CSVParserGeneratorInjectorProvider.class)
@SuppressWarnings("all")
public class CSVParserGeneratorParsingTest {
  @Inject
  private /* ParseHelper<Progam> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field CSVParserGeneratorParsingTest.parseHelper refers to the missing type Progam"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
