/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mdsd.parserGenerator.ui.internal.ParserGeneratorActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CSVParserGeneratorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ParserGeneratorActivator.getInstance().getInjector("dk.sdu.mdsd.CSVParserGenerator");
	}

}
