/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd.ui;

import com.google.inject.Injector;
import dk.sdu.mdsd.parserGenerator.ui.internal.ParserGeneratorActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CSVParserGeneratorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ParserGeneratorActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ParserGeneratorActivator activator = ParserGeneratorActivator.getInstance();
		return activator != null ? activator.getInjector(ParserGeneratorActivator.DK_SDU_MDSD_CSVPARSERGENERATOR) : null;
	}

}
