/*
 * generated by Xtext 2.21.0
 */
package dk.sdu.mdsd;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CSVParserGeneratorRuntimeModule extends AbstractCSVParserGeneratorRuntimeModule {
}
